name: Actualizador Semanal WoW

on:
  schedule:
    # Se ejecuta todos los martes a las 15:00 UTC (Aproximadamente a la hora del reset)
    - cron: '0 15 * * 2'
  workflow_dispatch: # ¡Esto nos crea un botón para ejecutarlo a mano cuando queramos!

permissions:
  contents: write # Permiso vital para que el robot pueda guardar el archivo en tu repositorio

jobs:
  actualizar:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Ejecutar el Robot Recolector
        env:
          BLIZZARD_CLIENT_ID: ${{ secrets.BLIZZARD_CLIENT_ID }}
          BLIZZARD_CLIENT_SECRET: ${{ secrets.BLIZZARD_CLIENT_SECRET }}
        run: python actualizar_datos.py

      - name: Guardar los nuevos datos en GitHub
        run: |
          git config --global user.name "Robot-WoW"
          git config --global user.email "robot@wowexplorador.com"
          git add datos.json
          git commit -m "Actualizar afijos de WoW" || echo "No hay cambios nuevos"
          git push
